### ISSUE TITLE
[Epic] Endpoints for user studies

### ISSUE THREAD

**Issue by tthvo** [open-ovi/api-server#1]
Users should be able to:

- [ ] Create a user study
- [ ] List a user study (i.e. all, by some attributes).
- [ ] Update a user study
- [ ] Archive a user study
- [ ] Delete a user study
